breadwallet/breadwallet-core

BRKey.c, BRKey.h, BRKeyECIES.c, BRPaymentProtocol.c
- moved BRECDH method into BRKey to make it accessible to the client apps
- removed duplicate implementation
=> refactor BRECDH method to be accessible via BRKey

BRKeyECIES.c, BRKeyECIES.h, module.modulemap
add Pigeon convenience functions to BRKeyECIES, add BRKeyECIES to the modulemap
=> CORE-111: encrypted message exchange functions

Swift/BRCrypto/implS/BRTransfer.swift
Model the amount and direction calculation after the iOS
appstore-3.12 branch's implementation of these operations.
=> CORE-322: Modify BRTransfer's direction and amount calculations

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/TransferBtc.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/WalletManagerBtc.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/bitcoin/BRTransaction.java, Java/Crypto/src/main/java/com/breadwallet/crypto/TransferDirection.java, Java/Crypto/src/main/java/com/breadwallet/crypto/WalletManagerState.java, Java/Crypto/src/main/java/com/breadwallet/crypto/WalletState.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/TransferDetailsActivity.java, Java/CryptoDemo/src/main/res/layout/activity_transfer_details.xml
Update the demo application to include direction as well, to help make sense of the transactions being displayed.
=> CORE-347: Set transaction state to included when confirmed tx is added

ripple/BRRippleTransaction.c, ripple/testRipple.c
I added a test to compare the actual content and found
that I was doing a memcpy on the wrong pointer
=> CORE-388: Fix bug in previous commit

crypto/BRCryptoTransfer.c, ethereum/ewm/BREthereumEWM.c, ethereum/ewm/BREthereumEWMClient.c
Add a missing `transactionCopy()` that lead to an ASAN issue.
=> CORE-508: In ETH, ensure an `estimatedFeeBasis` exists

Swift/BRCore.xcodeproj/project.pbxproj, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/common/BRBlockChainDB.swift, Swift/BRCrypto/common/BRSupport.swift, Swift/BRCryptoDemo/SummaryViewController.swift
DEPENDS on CORE-512.  Will merge in `crypto` once CORE-512 is there.
=> CORE-515: Make System defaults consistent w/ BDB

bitcoin/BRSyncManager.c, bitcoin/BRSyncManager.h, bitcoin/BRWalletManager.c, bitcoin/BRWalletManagerPrivate.h
@michael-brd Marked this as draft; is it is my notional implementation.
=> CORE-514: Report BTC/BCH P2P Sync Progress Every One Second

Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/HttpStatusCodes.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/PageInfo.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/PagedCompletionHandler.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/BdbApiClient.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/BlockApi.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/TransactionApi.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/brd/BrdApiClient.java, Swift/BRCrypto/common/BRBlockChainDB.swift
Draft for now, until api.blockset.com submission is restored.
=> CORE-524: Update HTTP status code handling

Java/CoreCrypto/src/androidTest/java/com/breadwallet/corecrypto/AddressAIT.java, Java/CoreCrypto/src/androidTest/java/com/breadwallet/corecrypto/NetworkAIT.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/CryptoApiProvider.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Network.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/NetworkDiscovery.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibrary.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoNetwork.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoNetwork.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/OwnedBRCryptoNetwork.java, Java/Crypto/src/androidTest/java/com/breadwallet/crypto/BlockchainDbAIT.java, Java/Crypto/src/main/java/com/breadwallet/crypto/Network.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/brd/EthTransferApi.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/Utilities.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Blockchain.java, Swift/BRCrypto/BRCryptoNetwork.swift, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/common/BRBlockChainDB.swift, Swift/BRCryptoTests/BRBlockChainDBTest.swift, Swift/BRCryptoTests/BRCryptoAccountTests.swift, Swift/BRCryptoTests/BRCryptoNetworkTests.swift, crypto/BRCryptoNetwork.c, crypto/BRCryptoNetwork.h, crypto/BRCryptoPrivate.h
=> CORE-530: Add Network.confirmationsUntilFinal

Swift/BRCrypto/BRCryptoSystem.swift
Note: this is untested and will be when merged into CORE-532 (Update Unit Tests)
=> CORE-536: Perform System Listener Events on a Dedicated Queue

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Account.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Utilities.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoAccount.java, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/common/BRSupport.swift
BDB produced such a timestamp.
=> CORE-567: Handle a pre-Unix timestamp of 1969-12-31T23:59:59.000+0000

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Blockchains.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/NetworkDiscovery.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Currency.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/CurrencyDenomination.java, Swift/BRCrypto/BRCryptoSystem.swift
Floor'ed to the nearest 5K boundary. Took the opportunity to refactor the Java to consolidate some of the builtin/supported/default constants.
=> CORE-573: Seed the supported blockchains w/ their current height

ethereum/ewm/BREthereumEWM.c
Reduces "ETH: EWM..." repetitive output.
=> CORE-582: In Core Ethereum, ease logging of ewmHandle{Transaction,Log}()

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Account.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibrary.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoAccount.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoAccount.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/OwnedBRCryptoAccount.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/CoreCryptoApplication.java, Swift/BRCrypto/BRCryptoAccount.swift, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCryptoDemo/CoreDemoAppDelegate.swift, crypto/BRCryptoAccount.c, crypto/BRCryptoAccount.h
=> CORE-583: In Core Crypto, the FileService is Account specific.

Swift/BRCrypto/common/BRBlockChainDB.swift, Swift/BRCryptoTests/BRCryptoBaseTests.swift, Swift/BRCryptoTests/BRCryptoWalletManagerTests.swift, crypto/BRCryptoWallet.c, crypto/BRCryptoWalletManager.c, ethereum/bcs/BREthereumBCS.c
Get the unit tests to compile too.
=> CORE-551: Address static analysis issues 

generic/BRGeneric.h, generic/BRGenericHandlers.h, generic/BRGenericRipple.c, generic/BRGenericWalletManager.c, generic/BRGenericWalletManager.h
=> CORE-595: In Core Ripple, Define `gwmRecoverTransfer`

Swift/BRCrypto/BRCryptoSystem.swift, crypto/BRCryptoWalletManagerClient.c, crypto/BRCryptoWalletManagerClient.h
Added funcGetTransfers in BRCryptoSystem
Added cwmAnnounceGetTransfersComplete
Added cwmAnnounceGetTransferItemGEN
- plus required enums
=> CORE-597: Update `BRCryptoCWMClientGEN` with `funcGetTransfers`

crypto/BRCryptoWallet.c, crypto/BRCryptoWalletManagerClient.c
Created a new function cryptoWalletGenerateBalance which is
called for GEN wallets from cryptWalletGetBalance
Once the announcing of tranfers complete - trigger a balance update
=> CORE-610: Calculate crypto wallet balance

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Network.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibrary.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoNetwork.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoNetwork.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/OwnedBRCryptoNetwork.java, Java/Crypto/src/main/java/com/breadwallet/crypto/System.java, Java/Crypto/src/main/java/com/breadwallet/crypto/errors/NetworkFeeUpdateError.java, Java/Crypto/src/main/java/com/breadwallet/crypto/errors/NetworkFeeUpdateFeesUnavailableError.java, Java/Crypto/src/main/java/com/breadwallet/crypto/events/network/DefaultNetworkEventVisitor.java, Java/Crypto/src/main/java/com/breadwallet/crypto/events/network/NetworkFeesUpdatedEvent.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/WalletListActivity.java, Java/CryptoDemo/src/main/res/menu/menu_wallet_list.xml, Swift/BRCrypto/BRCryptoNetwork.swift, Swift/BRCryptoDemo/CoreDemoAppDelegate.swift, Swift/BRCryptoDemo/SummaryViewController.swift, crypto/BRCryptoNetwork.c, crypto/BRCryptoNetwork.h, crypto/BRCryptoPrivate.h
@EBGToo, I noticed the Swift sets the networks fees at the Swift level only (I implemented the Java in the same way). Did we want to set those values at the C level?
=> CORE-506: Add System.updateNetworkFees

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Transfer.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/WalletManager.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoWalletManager.java, Java/Crypto/src/main/java/com/breadwallet/crypto/System.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/CoreSystemListener.java, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/BRCryptoWalletManager.swift, Swift/BRCryptoDemo/CoreDemoAppDelegate.swift, Swift/BRCryptoDemo/CoreDemoListener.swift, crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManager.h
=> CORE-617: In Core Crypto, cryptoWalletManagerCreate() can return NULL.

bitcoin/BRPeer.c
I checked the call hierarchy to confirm that `_BRPeerOpenSocket` is never called with the `ctx-lock` held.
=> CORE-657: In _BRPeerOpenSocket protect `ctx->socket`

Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/WalletListActivity.java, Java/CryptoDemo/src/main/res/layout/layout_wallet_item.xml, bitcoin/BRSyncManager.c
@EBGToo, creating as draft, pending comment from @ewerx on the behaviour.
=> CORE-681: Report BTC P2P sync progress based on last full sync

Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/Utilities.java
Removed unused helpers at the same time.
=> CORE-739: Update BDB JSON parsers to handle integer types

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibraryDirect.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManager.java, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCryptoDemo/Base.lproj/Main.storyboard, Swift/BRCryptoDemo/TransferTableViewCell.swift, crypto/BRCryptoHash.c, crypto/BRCryptoTransfer.c, crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManagerClient.c, crypto/BRCryptoWalletManagerClient.h, generic/BRGeneric.c, generic/BRGeneric.h, generic/BRGenericManager.c, generic/BRGenericPrivate.h
When matching GEN BDB Transfers work hard to handle the ‘__fee__’.
Requires a Java update to `system.mergeTransfers()` and an argument addition to `cwmAnnounceGetTransferItemGEN()`
=> CORE-719: In BRGenericTransfer add a UIDS; Add genTransferEqual()

bitcoin/BRPeerManager.c, bitcoin/BRSyncManager.c, bitcoin/BRWalletManager.c, bitcoin/BRWalletManager.h, crypto/BRCryptoWalletManagerClient.c
@EBGToo, placing this in DRAFT for now as I test further but wanted early eyes on it and the approach. In API testing, things look good. Just waiting for a sync to confirm P2P behaviour.
=> CORE-742: Improve BTC transaction state handling in crypto

Swift/BRCore.xcodeproj/xcshareddata/xcschemes/Core.xcscheme, Swift/CoreTests/CoreTests.swift, bitcoin/BRPeerManager.c, bitcoin/test.c
As expected, I've completed multiple syncs with this and have not seen a failure in _peerRelayedBlock().
=> CORE-723: In _peerRelayedBlock() handle failures gracefully.

crypto/BRCryptoAccount.c, generic/BRGenericHedera.c, hedera/BRHederaAccount.c, hedera/BRHederaAddress.c, hedera/BRHederaAddress.h, hedera/testHedera.c
- Update the account version to 3.
- Add the Hedera account serialization/de-serialization to crytpo account.
- Implement the serialize/de-serialize in the hedera code.
=> CORE-694: In Core Hedera, update BRCryptoAccount version

Swift/BRCrypto/BRCryptoAccount.swift, include/BRCryptoAccount.h
=> CORE-433: Clarify cryptoAccountValidateSerialization()

Java/corecrypto/src/main/java/com/breadwallet/corecrypto/NetworkDiscovery.java, Swift/BRCrypto/BRCryptoSystem.swift
Discovered this while adding XRP.  Core had it as a builtin but BlockSet did not; we want all builtin blockchains to appear.  (They can be used in P2P mode but will fail if the API endpoint is dead).
=> CORE-787: In Generic Core System.configure(), bias to `supportedNetworks`.

Swift/BRCryptoDemo/SummaryViewController.swift, crypto/BRCryptoConfig.h
Update the builtin network, currency and denomination declarations to be consistent with BlockSet.  See https://gitlab.com/breadwallet/blockchain-db/merge_requests/182#note_268347771
=> CORE-792: Updated BRCryptoConfig.h

Swift/BRCrypto/BRCryptoAccount.swift, bitcoin/BRWallet.c, crypto/BRCryptoAccount.c, crypto/BRCryptoNetwork.c, crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManagerClient.c, generic/BRGenericBase.h, generic/BRGenericClient.h, generic/BRGenericManager.c, generic/BRGenericRipple.c, ripple/BRRippleSignature.h, ripple/BRRippleTransaction.c
These leaks were found when displaying and submitting XRP transfers but some of them applied outside of XRP.
I'll run some BTC, etc tests and perhaps add to this PR.
=> CORE-793: Address Memory Leak Issues

Swift/BRCore.xcodeproj/project.pbxproj, Swift/BRCryptoDemo/Assets.xcassets/LogoGradientLarge.imageset/Contents.json, Swift/BRCryptoDemo/Assets.xcassets/LogoGradientLarge.imageset/LogoGradientLarge.pdf, Swift/BRCryptoDemo/Base.lproj/LaunchScreen.storyboard, Swift/BRCryptoDemo/Base.lproj/Main.storyboard, Swift/BRCryptoDemo/Info.plist, Swift/BRCryptoDemo/Initial Screen.storyboard
Only demo app UI changes (IOS).  Allows the App to be visible (not white on white) on an actual device.
=> CORE-800: Make the Core Demo App respect 'systemBackground'

crypto/BRCryptoWalletManager.c
[Marked as pending; because built on CORE-797; will rebase once CORE-797 is merged]
Please review the CORE-798 commit.
=> CORE-798: In `cryptoWalletManagerEstimateLimit()` respect balance limits

Swift/BRCrypto/BRCryptoWallet.swift, crypto/BRCryptoWalletManager.c, include/BRCryptoWalletManager.h
I created a Java JIRA for this.  There is another change to `createTransfer` coming; will handle everything in that ticket.
=> CORE-801: For GEN, generate a TransferEvent.created

Swift/BRCrypto/BRCryptoTransfer.swift, Swift/BRCrypto/BRCryptoWallet.swift, Swift/BRCryptoDemo/Base.lproj/Main.storyboard, Swift/BRCryptoDemo/TransferCreateSendController.swift, Swift/BRCryptoTests/BRCryptoWalletTests.swift, crypto/BRCryptoTransfer.c, crypto/BRCryptoTransferP.h, crypto/BRCryptoWallet.c, generic/BRGeneric.c, generic/BRGeneric.h, generic/BRGenericBase.h, generic/BRGenericHandlers.h, generic/BRGenericRipple.c, include/BRCryptoTransfer.h, include/BRCryptoWallet.h, ripple/BRRippleTransaction.c, ripple/BRRippleTransaction.h, ripple/BRRippleWallet.c, ripple/testRipple.c
[Java work covered in CORE-807]  There are things to discuss about this Swift implementation (use of a value type for `TransferAttribute`) that might need to change after discussing Java implementation.  But, looking to get PR in place and willing to modify later.
=> CORE-799: Add TransferAttribute

Swift/BRCore.xcodeproj/project.pbxproj, bitcoin/BRBloomFilter.c, bitcoin/BRMerkleBlock.c, bitcoin/BRPeer.c, bitcoin/BRPeerManager.c, support/BRBase.h, support/BRFileService.c, support/BRKey.c
@voisine What do you think about these uses of `ANALYZER_IGNORE_UNREAD_VARIABLE` to quit Static Analyzer warning (and document that we've analyzed the warning)?
=> CORE-250: Address Static-Analysis Warnings

Swift/BRCryptoTests/BRCryptoTransferTests.swift, bitcoin/BRWallet.c, bitcoin/BRWallet.h, bitcoin/BRWalletManager.c, support/BRAddress.c, support/BRAddress.h
Also modifies BRWalletManager.c to address possible P2P issues seen in IOS related to 'isDeleted'
=> CORE-853: check tx signature/witness for wallet inclusion

generic/BRGenericManager.c
Don't update the `brdSync.begBlockNumber` unless `success`.
=> CORE-873: For a periodic GEN sync, handle a get{Transfers,Transactions} Failure

bitcoin/BRWalletManager.c
=> CORE-874: In `bwmHandleTxAdded()`, don't dereference `refedTransaction`
