BRWallet.c
The transaction has an 0BTC change amount, in the following condition:
current wallet balance == amount to spend && feeAmount == minAmount 
In this case, the following condition is TRUE (at line 645) and it adds the 0BTC change output:
```
else if (transaction && balance - (amount + feeAmount) >= minAmount) { // add change output
```
Note: same problem if the balance satisfied the following condition:
balance == minAmount + amount + feeAmount
=> Fix 0 change output

BRBIP38Key.c
Source https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki#specification
This fixes sweeping private keys with a password.
=> BIP38 Uses Base58Check to do its validation not bech32

Java/Core/src/main/cpp/jni/com_breadwallet_core_BRCoreTransactionInput.c
If you create an input using large Satoshi amounts, for example anything over the maximum amount for uint32_t, the resulting input will be returned with an amount value less than expected. uint32_t is not large enough for this cast and the type being cast to is type uint64_t, so it seems sensible to change the cast to be the same.
https://github.com/breadwallet/breadwallet-core/blob/4081fc8967a59949a04b7023fb643aff91c215be/bitcoin/BRTransaction.h#L54
createTransactionOutput already casts the jlong amount to uint64_t.
https://github.com/breadwallet/breadwallet-core/blob/4081fc8967a59949a04b7023fb643aff91c215be/Java/Core/src/main/cpp/jni/com_breadwallet_core_BRCoreTransactionOutput.c#L35
=> Larger cast to avoid narrowing

Java/Core/src/main/java/com/breadwallet/core/ethereum/BREthereumEWM.java
That method is called in a JNI callback ‘trampoline’ thread and modifies the `tokensByReference` and `tokensByAddress` HashMaps.  That modification leads to a `java.util.ConcurrentModificationException` when other threads are reading the HashMaps.
=> CORE-368: Synchronize BREthereumEWM::addTokenByReference.

ethereum/ewm/BREthereumEWMClient.c
For Ethereum, ensure that installed tokens are consistent w/ the network.  Specifically, the 'getTokens' BRD endpoint only provides 'mainnet' tokens.
=> CORE-381: For ethereumTestnet install proper tokens (for BRD and TST).

ripple/BRRippleAccount.c, ripple/BRRippleAccount.h, ripple/BRRippleTransaction.c, ripple/BRRippleTransaction.h, ripple/testRipple.c
1. Remove the unneeded BRRippleSeralizedTransaction structure
and just have methods on the transaction to get at the bytes
2. When a user asks for serialized bytes, allocate a new buffer,
copy the bytes and then they can simply free a uint8_t pointer
3. When a user creates a transaction via raw bytes from the server,
store those bytes with the transaction so they can retrieve later
=> CORE-388: Change the serialize functions

Java/Core/src/main/cpp/jni/ethereum/com_breadwallet_core_ethereum_BREthereumEWM.c, Java/Core/src/main/cpp/jni/ethereum/com_breadwallet_core_ethereum_BREthereumEWM.h, Java/Core/src/main/java/com/breadwallet/core/ethereum/BREthereumEWM.java, Java/Core/src/main/java/com/breadwallet/core/ethereum/BREthereumTransfer.java
Added Transfer:isErrored (analogous to isConfirmed() and isSubmitted()) and Transfer:getErrorDescription (NULL if not isErrored()).
This change does not touch BTC code.  This change parallels existing functions in Java/JNI.
=> CORE-384: For Java Core Ethereum, expose a Transfer’s error status.

Java/CoreCrypto/src/androidTest/java/com/breadwallet/corecrypto/AccountAIT.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Account.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/CryptoApiProvider.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/WalletManager.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibrary.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManager.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoAccount.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoWalletManager.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/OwnedBRCryptoWalletManager.java, Java/Crypto/src/main/java/com/breadwallet/crypto/Account.java, Java/Crypto/src/main/java/com/breadwallet/crypto/CryptoApi.java, Java/Crypto/src/main/java/com/breadwallet/crypto/WalletManager.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/CoreCryptoApplication.java
In Java, Strings are immutable so they can't be explicitly be cleared in memory. We'd be relying on the JVM to eventually clear it out based on its internal memory usage.
Instead, switch to requiring secret material to be passed as UTF-8 encoded byte arrays. This allows the caller to explicitly zero out the array in question once the secret has been used.
In addition, don't rely on JNA's marshalling for handling the byte array to avoid the potential for copies to be made. Instead, allow the memory directly, fill it and clear it after use.
=> CORE-397: Improve handling of paper key / phrase in Java

Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Blockchain.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Currency.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/CurrencyDenomination.java, Swift/BRCrypto/common/BRBlockChainDB.swift, Swift/BRCryptoTests/BRBlockChainDBTest.swift
Reword the builtin blockchain and currencies to use the correct name for BCH
=> CORE-389: For “bch” use “Bitcoin Cash”

Java/CoreCrypto/src/androidTest/java/com/breadwallet/corecrypto/AccountAIT.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Account.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/CryptoApiProvider.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibrary.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoAccount.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoAccount.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/OwnedBRCryptoAccount.java, Java/Crypto/src/main/java/com/breadwallet/crypto/Account.java, Java/Crypto/src/main/java/com/breadwallet/crypto/CryptoApi.java, Swift/BRCrypto/BRCryptoAccount.swift, Swift/BRCryptoTests/BRCryptoAccountTests.swift, crypto/BRCryptoAccount.c, crypto/BRCryptoAccount.h
Add account serialization.  Once an account is created, based on a `phrase` (aka 12-word BIP-39 'paper key') it can be serialized and then recreated from the serialization.  Doing so avoids using the sensitive 'paper key' whenever the account needs to be created.
We anticipate that that serialization will change; specifically anytime a new blockchain is added.  In such a case the new blockchain's public key needs to be serialized.  For example, when adding XRP (Ripple) the XRP public key must be serialized.  On a change recreating the account from the serialization will fail and the 'paper key' must be used to recreate the account.
=> CORE-401: Account serialization

Java/Core/src/androidTest/java/com/breadwallet/core/ethereum/ClientAIT.java, Java/Core/src/main/cpp/jni/ethereum/com_breadwallet_core_ethereum_BREthereumEWM.c, Java/Core/src/main/cpp/jni/ethereum/com_breadwallet_core_ethereum_BREthereumEWM.h, Java/Core/src/main/java/com/breadwallet/core/ethereum/BREthereumEWM.java
Expose in the BREthereumEWM constructors.  This allows the Android App to select the desired mode; previously it was hardcoded.
=> CORE-416: Define Java BREthereumEWM.Mode as {API_ONLY, ..., P2P_ONLY}

ripple/BRRippleAccount.c, ripple/BRRippleAccount.h, ripple/testRipple.c
Create an account with both serialized account bytes and with a public key.
Add unit tests to confirm.
All existing unit tests passed.
=> CORE-414 Confirm Ripple Account Creation from a Public Key

bitcoin/BRWalletManager.c, bitcoin/BRWalletManager.h, bitcoin/test.c, crypto/BRCryptoWalletManager.c, ethereum/bcs/BREthereumBCS.h, ethereum/ewm/BREthereumEWM.c, ethereum/ewm/BREthereumEWM.h, ethereum/ewm/BREthereumEWMPrivate.h, ethereum/ewm/testEwm.c
This allows a sync to start immediately rather than, in API modes, after one full period.
=> CORE-412: Initialize WalletManagers w/ the Network Block Height

Swift/BRCrypto/common/BRBlockChainDB.swift, Swift/BRCrypto/common/BRSupport.swift
The nature of a BTC sync is that each transaction may use new addresses.  When querying the BDB all these addresses must be provided in the HTTP request.  Apparently the number of address overflowed the HTTP request limit and later transactions request (when addresses had accumulated) had failed.  The IOS App missed finding known transactions.  So, split the request into at most ADDRESS_COUNT addresses (currently 50).
=> CORE-413: In Swift Core Crypto BlockchainDB, 'chunk' addresses in

Java/CoreCrypto/src/androidTest/java/com/breadwallet/corecrypto/NetworkAIT.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Network.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/NetworkDiscovery.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/NetworkFee.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/WalletManager.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibrary.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoNetwork.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoNetworkFee.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoNetwork.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoNetworkFee.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/OwnedBRCryptoNetwork.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/OwnedBRCryptoNetworkFee.java, Java/Crypto/src/main/java/com/breadwallet/crypto/Network.java, Java/Crypto/src/main/java/com/breadwallet/crypto/NetworkFee.java, Java/Crypto/src/main/java/com/breadwallet/crypto/WalletManager.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Blockchain.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/BlockchainFee.java, Swift/BRCrypto/BRCryptoNetwork.swift, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/BRCryptoWallet.swift, Swift/BRCrypto/BRCryptoWalletManager.swift, Swift/BRCrypto/common/BRBlockChainDB.swift, Swift/BRCryptoTests/BRBlockChainDBTest.swift, Swift/BRCryptoTests/BRCryptoAccountTests.swift, Swift/BRCryptoTests/BRCryptoNetworkTests.swift, crypto/BRCryptoNetwork.c, crypto/BRCryptoNetwork.h, crypto/BRCryptoPrivate.h
Derive from BlockchainDB `fee_estimates`.  Keep an (unsorted) array in `Network`; allow for saving a default in `WalletManager`.
Does not yet propagate to `Wallet.createTransfer`.
=> CORE-340: Create BRCryptoNetworkFee

Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/brd/BrdApiClient.java, Swift/BRCrypto/common/BRBlockChainDB.swift
Needs Java update - are API ethq/testnet/proxy requests working?  It should be ethq/ropsten/proxy where 'ropsten' is an alternate name for 'testnet'.  We use 'testnet' throughout; the API needs 'ropsten' - thus I only changed the HTTP query path.
=> CORE-450: Use ethq/ropsten/query in JSON RPC requests.

Java/CoreCrypto/src/androidTest/java/com/breadwallet/corecrypto/KeyAIT.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/CryptoApiProvider.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Key.java, Java/CoreNative/CMakeLists.txt, Java/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibrary.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoKey.java, Java/Crypto/src/main/java/com/breadwallet/crypto/CryptoApi.java, Java/Crypto/src/main/java/com/breadwallet/crypto/Key.java
Bonus, this establishes a pattern where we don't need the CoreBRCryptoXyz and corresponding OwnedBRCryptoXyz classes.
I will create a ticket to (at some point) convert everything to this new pattern.
=> CORE-451: Add CryptoKey in Java

Swift/CoreTests/CoreTests.swift, ripple/BRRippleAccount.c, ripple/testRipple.c
Fixed the unit test - we do not need to allow
for creating of account from private key. I was
able to create a new unit test to validate creating
of the transaction id
Remove unused code from the account file. It was only used
for testing and I now test a different way.
=> CORE-466: Fix Ripple unit test

crypto/BRCryptoAmount.c, crypto/testCrypto.c, ethereum/util/BRUtilMath.c, ethereum/util/BRUtilMath.h, ethereum/util/testUtil.c
Reimplement `cryptoAmountCreateDouble` to accept an arbitrary double - instead of a double that needed to be less than INT64_MAX (sigh).
=> CORE-417: Add createUInt256Double()

crypto/BRCryptoWallet.c
Adding transfer directly in createTransfer routine caused ETH assert on NULL == transfer in BRCryptoWalletManagerClient's TRANSFER_EVENT_CREATED handler.
I believe the pattern we've established is that transfers are added in their event handler so restoring that pattern with this commit.
In my testing, transfer status events (created, submitted, included) are all propagated correctly.
=> CORE-311: Remove unnecessary transfer add that triggered assert

ripple/testRipple.c
Unit test had bad data - an array with no terminating byte.
=> CORE-476: Xcode ASAN Detects Error in Test Code

Java/CoreCrypto/src/androidTest/java/com/breadwallet/corecrypto/AmountAIT.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Amount.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Transfer.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/TransferFeeBasis.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Utilities.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Wallet.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibrary.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoAmount.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoAmount.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/OwnedBRCryptoAmount.java, Java/Crypto/src/main/java/com/breadwallet/crypto/Amount.java, Swift/BRCrypto/BRCryptoAmount.swift, Swift/BRCrypto/BRCryptoNetwork.swift, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/BRCryptoTransfer.swift, Swift/BRCrypto/BRCryptoWallet.swift, Swift/BRCryptoTests/BRCryptoAmountTests.swift, crypto/BRCryptoAmount.c, crypto/BRCryptoAmount.h, crypto/BRCryptoFeeBasis.c, crypto/BRCryptoPrivate.h, crypto/BRCryptoTransfer.c, crypto/BRCryptoWallet.c, crypto/BRCryptoWalletManagerClient.c
This changes the initializer of `Amount(core:unit:take)` into just `Amount(core:take)` making it analogous to *all* other initializers given a Crypto C instance.  Importantly, in some Swift/Java contexts, the Unit does not need to be held as it is 100% provided by Crypto C.  (TransferConfirmation's fee as one example).
Requires Java changes.
=> CORE-421: Move Amount.unit into BRCryptoAmount

Swift/BRCore.xcodeproj/xcshareddata/xcschemes/BRCrypto.xcscheme, Swift/BRCrypto/BRCryptoNetwork.swift, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/BRCryptoTransfer.swift, Swift/BRCrypto/BRCryptoWallet.swift, Swift/BRCrypto/BRCryptoWalletManager.swift, Swift/BRCrypto/common/BRSupport.swift, Swift/BRCryptoTests/BRCryptoBaseTests.swift, Swift/BRCryptoTests/BRCryptoSystemTests.swift, Swift/BRCryptoTests/BRCryptoTransferTests.swift, Swift/BRCryptoTests/BRCryptoWalletManagerTests.swift, Swift/BRCryptoTests/BRCryptoWalletTests.swift, crypto/BRCryptoTransfer.c
This does not completely cover the WalletManager, Wallet and Transfer interface - but, aside from 'submit', it is pretty good.  Would expect to add more tests as some existing bugs are fixed.
This is all in Swift; certain things must be; some others could be in C, at some point.
This does include a merge from CORE-480 (EWM Event Handlers) and we'd expect CORE-480 to be reworked in a future merge to 'crypto'
=> CORE-478: Extend BRCrypto{WalletManager, Wallet, Transfer} Tests.

Java/Core/CMakeLists.txt, Java/CoreNative/CMakeLists.txt, Swift/BRCore.xcodeproj/project.pbxproj, Swift/BRCrypto/BRCryptoTransfer.swift, bitcoin/BRWalletManager.c, bitcoin/BRWalletManager.h, crypto/BRCryptoFeeBasis.c, crypto/BRCryptoPrivate.h, crypto/BRCryptoTransfer.c, crypto/BRCryptoWallet.c, crypto/BRCryptoWalletManagerClient.c, ethereum/base/BREthereumBase.h, ethereum/base/BREthereumFeeBasis.c, ethereum/base/BREthereumFeeBasis.h, ethereum/blockchain/BREthereumTransaction.c, ethereum/blockchain/BREthereumTransaction.h, ethereum/ewm/BREthereumBase.h, ethereum/ewm/BREthereumEWM.c
Add `BRCryptoFeeBasis feeBasisConfirmed` to `struct BRCryptoTransferRecord`; set `feeBasisConfirmed` when a transfer (BTC, ETH, etc) is TRANSFER_INCLUDED.  Set feeBasisEstimated when created - either directly upon `cryptoWalletCreateTransfer()` or after the fact when the BTC, ETH, etc `TRANSFER_CREATED` event is handled.
Created as a draft until CORE-478/PR-148 is merged - so tests can be extended.  (However, in a test merge of CORE-478, previously failing unit tests are fixed by this CORE-492 branch.)
=> CORE-492: Implement cryptoTransferGetConfirmedFeeBasis()

crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManagerClient.c, ethereum/event/BREvent.c, ethereum/ewm/BREthereumEWM.c, ethereum/ewm/BREthereumEWM.h
CWM will call ewmCreate(...), set up `cwm` and `cwm->wallet`, and then call `ewmStart()` to generate EWM events.  It might be that CWM doesn't need to generate its own CWM events (in cwmCreate()) as the EWM events, once flowing, will generate CWM events(?).
=> CORE-480: Start the EWM event handler on `ewmStart()` not on `ewmConnect()`.

Swift/BRCrypto/BRCryptoSystem.swift, crypto/BRCryptoWalletManagerClient.c, ethereum/ewm/BREthereumClient.h, ethereum/ewm/BREthereumEWM.c, ethereum/ewm/BREthereumEWMClient.c, ethereum/ewm/BREthereumEWMEvent.c, ethereum/ewm/BREthereumEWMPrivate.h, ethereum/ewm/testEwm.c
(Done in support of CORE-486 and CORE-491)
Ethereum event interfaces passed `(..., event (as an enum), status, error )`.  Changed to be 
```
typedef struct {
type,
status,
union { /* event specific data */} u;
error
} event;
```
This structured approach allows one to pass values back in an event.
=> CORE-305: Rework Ethereum Events

Swift/BRCrypto/BRCryptoAmount.swift, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/BRCryptoTransfer.swift, Swift/BRCryptoTests/BRCryptoCommonTests.swift, Swift/BRCryptoTests/BRCryptoDebugSupport.swift, Swift/BRCryptoTests/BRCryptoTransferTests.swift, Swift/BRCryptoTests/BRCryptoWalletManagerTests.swift, bitcoin/BRWalletManager.c, bitcoin/BRWalletManager.h, crypto/BRCryptoPrivate.h, crypto/BRCryptoTransfer.c, crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManager.h, support/BRFileService.c, support/BRFileService.h
Note that the 'Random Cleanup' has unrelated changes (in BRCryptoAmount.swfit, BRCryptoTransfer.swift, BRCryptoCommonTests.swift, and BRCryptoTransferTests.swift)
Includes changes to BRFileService to add a fileServiceCreateFromTypeSpecfications() - so that BRWalletManagerNew() and BRWalletManagerCreateFileService() can produce the same BRFileService for BTC.
=> CORE-282: BRCryptoWalletMigrator

Java/CoreCrypto/src/androidTest/java/com/breadwallet/corecrypto/AddressAIT.java, Swift/BRCryptoTests/BRCryptoAccountTests.swift, Swift/BRCryptoTests/BRCryptoBaseTests.swift, Swift/BRCryptoTests/BRCryptoTransferTests.swift, Swift/BRCryptoTests/BRCryptoWalletTests.swift, bitcoin/BRWalletManager.c, bitcoin/BRWalletManager.h, bitcoin/test.c, crypto/BRCryptoAddress.c, crypto/BRCryptoAddress.h, crypto/BRCryptoNetwork.c, crypto/BRCryptoPrivate.h, crypto/BRCryptoTransfer.c, crypto/BRCryptoWallet.c, crypto/BRCryptoWalletManagerClient.c
The behavior with testnet is pending.  (BCH testnet has unexpected behavior; a BTC testnet test case is needed).
=> CORE-437: In BRCryptoAddress, handle bitcoin cash addresses

Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Blockchain.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Currency.java, Swift/BRCrypto/common/BRBlockChainDB.swift, ethereum/blockchain/BREthereumBlock.c
Set the Rinkeby checkpoint timestamp for the genesis block to 0 - which means an arbitrary time in a checkpoint lookup will find the genesis block.
Axe Rinkeby as a default network (it will *never* be provided by BDB)
=> CORE-511: Rinkeby Updates

Java/CoreCrypto/src/androidTest/java/com/breadwallet/corecrypto/AddressAIT.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/NetworkDiscovery.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Blockchain.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/BlockchainFee.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Currency.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/CurrencyDenomination.java, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/common/BRBlockChainDB.swift, Swift/BRCrypto/common/BRSupport.swift, Swift/BRCryptoDemo/SummaryViewController.swift
Java changes pending.  Note: in the blockchain+currencies declarations 'ethereum-testnet' changed to 'ethereum-ropsten' to be consistent with BDB.
=> CORE-512: Handle a BDB blockHeight of `-1` (not supported)

Swift/BRCrypto/common/BRBlockChainDB.swift
Previously, bdbMakeRequest() passed a 'more:Bool' flag to the completion handler; now it passes a 'more:URL?' to indicate if more data remains and the URL should be hit.
=> CORE-510: Process BDB 'next:href' links

Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/TransactionApi.java, bitcoin/BRSyncManager.c
Small change in Java to a) align the address count with Swift and b) order the params so that I can see the start/end numbers in logcat (were previously being cut off when they were at the end).
=> CORE-391: Do not re-query addresses when new ones are discovered

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCryptoTests/BRCryptoSystemTests.swift
=> CORE-527: Support `.api_only` for all blockchains.

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/NetworkDiscovery.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/Crypto/src/main/java/com/breadwallet/crypto/System.java, Java/Crypto/src/main/java/com/breadwallet/crypto/events/system/DefaultSystemEventVisitor.java, Java/Crypto/src/main/java/com/breadwallet/crypto/events/system/SystemDiscoveredNetworksEvent.java, Java/Crypto/src/main/java/com/breadwallet/crypto/events/system/SystemEventVisitor.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/CoreCryptoApplication.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/CoreSystemListener.java, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCryptoDemo/CoreDemoAppDelegate.swift, Swift/BRCryptoDemo/CoreDemoListener.swift, Swift/BRCryptoTests/BRCryptoBaseTests.swift, Swift/BRCryptoTests/BRCryptoSystemTests.swift, Swift/BRCryptoTests/BRCryptoWalletManagerTests.swift, crypto/BRCryptoUnit.c, crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManagerClient.c
This PR is 'double drafty'.
Probably the most important change is in BRCryptoWalletManager in the `create()` function (for ETH).  No longer is the ETH callback getTokens invoked; instead the network currencies (and the corresponding default unit) are used to a) create an ETH token and b) create an ETH wallet for that token.  The creation of the ETH wallet 'flows through the callbacks' to a) create an CWM wallet, and b) get announced via Swift/Java WalletManager and Wallet events.  [It may be that this change **is not** needed - it was originally made expecting (hoping) that the wallets would get announced immediately - that didn't happen]
Another change is to perform the system.configure action on the system.queue and to have that queue wait until all blockshains+currencies have produced …
=> CORE-531: Produce a SystemEvent When All Networks are Discovered

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/WalletManager.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibrary.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManager.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoWalletManager.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/OwnedBRCryptoWalletManager.java, Java/Crypto/src/main/java/com/breadwallet/crypto/System.java, Java/Crypto/src/main/java/com/breadwallet/crypto/WalletManager.java, Java/CryptoDemo/src/main/AndroidManifest.xml, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/ConnectivityBroadcastReceiver.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/CoreCryptoApplication.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/CoreSystemListener.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/Utilities.java, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/BRCryptoWalletManager.swift, bitcoin/BRSyncManager.c, bitcoin/BRSyncManager.h, bitcoin/BRWalletManager.c, bitcoin/BRWalletManager.h, crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManager.h
@EBGToo, I've updated the Java demo app to announce connectivity changes. I also exposed setNetworkReachable on both System and WalletManager.
I had thought to originally only have it on System but then the case comes up where a WalletManager comes in later on. We *could* have the System cache the value and apply it all created WalletManagers but then it gets a bit "stateful". Thought ultimately this was the most direct way to do it.
BRWalletManager defaults to TRUE for networkIsReachable, rather than expose it in the BRWalletManagerNew as a param (that function already has a ton of params). The comment highlights that this is in the (likely) case where a client doesn't bother keeping the flag up to date (ex: if this is running on a server that doesn't care/monitor network status).
=> CORE-538: Expose function to set if the network is reachable

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Swift/BRCore.xcodeproj/xcshareddata/xcschemes/Core.xcscheme, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/common/BRBlockChainDB.swift, Swift/BRCryptoTests/BRBlockChainDBTest.swift, Swift/BRCryptoTests/BRCryptoBaseTests.swift, Swift/BRCryptoTests/BRCryptoTransferTests.swift, Swift/BRCryptoTests/BRCryptoWalletManagerTests.swift, Swift/BRCryptoTests/BRCryptoWalletTests.swift, Swift/BRCryptoTests/BRSupportTests.swift, ethereum/ewm/testEwm.c
Includes a fix in Swift and Java to the `supportedAddressSchemes` map to use 'bitcoincash-testnet' (not 'bitcoin-cash-testnet')
The test `testsTransferBTC_P2P()` fails; captured as CORE-546
The code adds in the BRD token on Testnet; needed in Java
There is a wallet name test that uses "eth" and "BRD"; someday "eth" will be "ETH".
=> CORE-532: Updated Unit Tests

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/WalletManager.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibrary.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManager.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/CoreBRCryptoWalletManager.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/OwnedBRCryptoWalletManager.java, Java/Crypto/src/main/java/com/breadwallet/crypto/System.java, Java/Crypto/src/main/java/com/breadwallet/crypto/WalletManager.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/CoreSystemListener.java, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/BRCryptoWalletManager.swift, Swift/BRCryptoDemo/CoreDemoAppDelegate.swift, Swift/BRCryptoDemo/CoreDemoListener.swift, crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManager.h
What is your feeling on this.  I think `requireWalletFor(...)` returning `Wallet?` is a bit awkward - unlike other interfaces.
It might be better to axe this function (as least publicly) and provide something at the `System` level.  Thinking...
Maybe add a `currencies: [Currency]` argument to `<system>.createWalletManager (..., currencies)`?  The `createWalletManager` call occurs in .networkAdded so all the currencies are known; they can be filtered by the App and then handled on CWM create.  <== This is better, no?
=> CORE-561: In Core Crypto, Add WalletManager.registerWalletFor(currency).

Swift/BRCryptoDemo/CoreDemoAppDelegate.swift, ethereum/ewm/BREthereumEWM.c
The ETH code says:
```
// Create a default ETH wallet; other wallets will be created 'on demand'.
```
and then it went ahead and created the others.  Thankfully they truly are 'on-demand', via `ewmHandleLog()` - called in both API and P2P modes.
Maybe next time test with `clearPersistentData` set to both `true` and `false`?
=> CORE-584: In Core Ethereum, during ewmCreate(), don't create ERC20 wallets up-front.

Swift/BRCryptoTests/BRCryptoDebugSupport.swift
This was leading to a unit test success... except the test should have failed.
=> CORE-562: In Core Crypto Swift, Ensure EventMatcher Over Arrays Matches At Least One Element

ethereum/rlp/BRRlpCoder.c
The FileService holds an RLP Coder and a file service is now called via multiple threads.  Hence TSAN issues have arisen.
=> CORE-589: In Core Crypto, Address TSAN #2

ethereum/ewm/BREthereumEWM.c
Don't announce the 'lastBlock' height, which is at best old and at worst the earliestKeyTime checkpoint block.
=> CORE-599: In Core Ethereum, in `ewmCreate()` announce the provided `blockHeight`

Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/brd/EthBlockApi.java, Swift/BRCrypto/BRCryptoSystem.swift
A '0' indicates that the queried ETH node is in the process of syncing.
Requires a corresponding Java change.  [I did the validity check in the System.swift in `funcGetBlockNumber` for the ETH callbacks.  To me, the JSON-RPC returning "0" is wrong; it should be returning some 'error code' - so passing "0" along into CryptoC as an error flag is wrong.  But maybe I can be convinced otherwise.]
=> CORE-601: If the eth_blocknumber query produces '0', return Result.failure

Java/Core/CMakeLists.txt, Java/CoreNative/CMakeLists.txt, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/CoreCryptoApplication.java, Swift/BRCore.xcodeproj/project.pbxproj, Swift/BRCryptoDemo/CoreDemoAppDelegate.swift, ethereum/ewm/BREthereumEWM.c, ethereum/ewm/BREthereumEWMClient.c, ethereum/ewm/BREthereumEWMPersist.c, ethereum/ewm/BREthereumEWMPrivate.h, ethereum/ewm/BREthereumWallet.c, ethereum/ewm/BREthereumWallet.h, support/BRFileService.c, support/BRFileService.h
The balance is saved and restored for every wallet; the nonce only applies to the ETH wallet.  (Note: the nonce actually only applies the the account; but we hackily include it in the wallet state rather than introduce some other persistently stored type).
The balance is saved because it CAN NOT be derived from the sum of the transactions because Ethereum has some wacky, hacky concept of 'internal transactions' and we don't handle those (yet?).  We thus store the balance so that Core comes up with the last known balance (even if in airplane mode).
As the persistent types have grown, this PR moves the File Service specifications into a new file BREthereumEWMPersist.c
Also a fix the the Demo App to always ensure that the 'path' exists (pending CORE-600).  When I changed to a new simulator, …
=> CORE-598: In Core Ethereum, Persistently Store Balance and Nonce

crypto/BRCryptoWalletManagerClient.c, generic/BRGenericHandlers.h, generic/BRGenericRipple.c, generic/BRGenericWalletManager.c, generic/BRGenericWalletManager.h
Reworked the function as per the JIRA item.  For Ripple
the function returns NULL and no transfers are show.
=> CORE-593: In Core Ripple, Rework gwmRecoverTransfer

crypto/BRCryptoWalletManagerClient.c, generic/BRGenericHandlers.h, generic/BRGenericRipple.c, generic/BRGenericWalletManager.c, generic/BRGenericWalletManager.h
…saction based
Add support for the gen wallet to either call
- client.getTransactions OR
- client.getTransfers
based on a propery in the generic wallet manager
Also - add the client.getTransfers callback
=> CORE-602: In Core Ripple, Modify the GEN Wallet Manager to be either Transfer or Transaction based.

Swift/BRCore.xcodeproj/project.pbxproj, crypto/BRCryptoFeeBasis.c, generic/BRGenericHandlers.h, generic/BRGenericRipple.c, generic/BRGenericWalletManager.c, generic/BRGenericWalletManager.h, ripple/BRRippleAccount.c, ripple/BRRippleAccount.h, ripple/BRRippleBase.h, ripple/BRRippleFeeBasis.c, ripple/BRRippleFeeBasis.h, ripple/BRRippleTransaction.c, ripple/BRRippleTransaction.h, ripple/BRRippleTransfer.c, ripple/BRRippleWallet.c, ripple/BRRippleWallet.h, ripple/testRipple.c
1. Added feeBasis structure and functions to generic
2. Modified BRRippleFeeBasis to be a structure and store
the required fields to support BRCryptoFeeBasis functions
- modified unit tests and all run successfully
3. Added required functions in BRGenericWalletManager
3. Implemented the GEN features in BRCryptoFeeBasis
Tested that I can get the fee shown in the demo app.
=> CORE-619: add GEN feeBasis functions w/ Ripple Implementations

generic/BRGenericRipple.c
Get the target address using the rippleTransfer... function
(not rippleTransaction...)
This is the last transfer "getter" that needed to be changed
=> CORE-608: In Core Ripple: get values from transfer (not tx)

crypto/BRCryptoTransfer.c
1. Load in the source and target addresses when creating
a GEN transfer.
2. ALSO - noticed a bug in cryptoTransferGetDirection for GEN
transfers - it needed to return CRYPTO_TRANSFER_RECEIVED in one case.
=> CORE-609: In Core Ripple, load in GEN transfer properties

crypto/BRCryptoWalletManagerClient.c, ethereum/ewm/BREthereumEWM.c, ethereum/ewm/BREthereumEWMClient.c, ethereum/ewm/BREthereumEWMEvent.c, ethereum/ewm/BREthereumEWMPrivate.h
Start a sync immediately upon 'connect'; when 'complete' is announced for both 'transactions' and 'logs' immediately report 'syncEnded(success)' (rather than waiting for the next periodic dispatch).
=> CORE-447: Improve Core Ethereum Syncing

ethereum/event/BREventAlarm.c
@EBGToo, took a pretty conservative approach here. Just make sure that calculated expiration times are not in the past.
The app shouldn't ever assume real-time scheduling/behaviour so I think this is a fair change.
Tested by breaking while debugging, waiting a period of time and then resuming.  Without the change, timer fires for each missed period; with it, doesn't bother with missed periods.
Note that this change doesn't fix the event queue being swamped with periodic events in the case of a slow periodic dispatch function.
=> CORE-489: Ensure that alarm expiration times are not in the past

ethereum/event/BREvent.c
Tested using:
```
-            pthread_create(&handler->thread, &attr, (ThreadRoutine) eventHandlerThread, handler);
+            pthread_t temp;
+            pthread_create(&temp, &attr, (ThreadRoutine) eventHandlerThread, handler);
+            sleep (2);
+            handler->thread = temp;
```
Confirmed failure before (with the NULL guard removed) and success after. Forces the issue, which was gap between `handler->thread` being set in `eventHandlerStart` and the actual event handler thread asserting on that value.
=> CORE-564: Fix eventHandlerIsCurrentThread and eventHandlerIsRunning

Swift/BRCrypto/BRCryptoNetwork.swift, crypto/BRCryptoAddress.c, crypto/BRCryptoNetwork.c, crypto/BRCryptoPrivate.h, crypto/BRCryptoTransfer.c, crypto/BRCryptoWallet.c, crypto/BRCryptoWalletManager.c, generic/BRGeneric.c, generic/BRGeneric.h, generic/BRGenericBase.h, generic/BRGenericHandlers.h, generic/BRGenericRipple.c, generic/BRGenericWalletManager.c, generic/BRGenericWalletManager.h
1. Add the BRGenericNetwork interfacei, functions, and handlers
2. Implement the single handler function "createAddress"
3. Add a BRGenericNetwork to BRCryptoNetwork
4. Modify cryptoNetworkCreateAddressFromString to use the generic
network to create the address
5. Add a BRCryptoCurrency parameter to cryptoNetworkCreateAsGEN so
that it can create the correct BRGenericNetwork.
=> CORE-634: In Core Ripple, Define BRGenericNetwork

Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCryptoTests/BRCryptoBaseTests.swift, Swift/BRCryptoTests/BRCryptoSystemTests.swift, Swift/BRCryptoTests/BRCryptoTransferTests.swift, Swift/BRCryptoTests/BRCryptoWalletManagerTests.swift, Swift/BRCryptoTests/BRCryptoWalletTests.swift, ethereum/ewm/testEwm.c, support/testSup.c
Still failures: in a number of unit tests, the Wallet Manager event sequences don't match (generally a difference between P2P and API modes) and the balanceUpdated event in P2P mode reports a balance of 0.
This includes one fix to Swift code used in `configure`; important to be in the upcoming release (see BRCryptoSystem.swift)
=> CORE-638: Fix Core/BRCrypto Unit Tests

Swift/BRCore.xcodeproj/project.pbxproj, Swift/BRCryptoDemo/CoreDemoAppDelegate.swift, Swift/BRCryptoTests/BRCryptoBaseTests.swift, Swift/BRCryptoTests/BRCryptoTransferTests.swift, Swift/BRCryptoTests/BRCryptoWalletManagerTests.swift, Swift/BRCryptoTests/BRCryptoWalletTests.swift, Swift/InstallCoreTestsConfig.sh
Handle some BTC/ETH and API/P2P differences (but added a JIRA CORE-647 to reconcile).
=> CORE-646: In Core Crypto, Add 'common' checks to BRCryptoBaseTests for Swift

crypto/BRCryptoWallet.c, generic/BRGeneric.c, generic/BRGeneric.h, generic/BRGenericRipple.c, generic/BRGenericWalletManager.h
Added missing Release functions.
Also - while making changes did some formatting fixes for function defines/declarations
i.e. add space between name and "("
=> CORE-635: In Core Ripple, To 'Handler Types' Add a Release/Free handler

Swift/BRCrypto/BRCryptoSystem.swift
Confirmed w/ Ehsan in a debugging session.
=> CORE-558: In Core Crypto, Migrate Block Blobs w/ Correct Bytes.

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/Utilities.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManagerEvent.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManagerEventType.java, Java/Crypto/src/main/java/com/breadwallet/crypto/events/walletmanager/DefaultWalletManagerEventVisitor.java, Java/Crypto/src/main/java/com/breadwallet/crypto/events/walletmanager/WalletManagerEventVisitor.java, Java/Crypto/src/main/java/com/breadwallet/crypto/events/walletmanager/WalletManagerSyncRecommendedEvent.java, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/BRCryptoWalletManager.swift, Swift/BRCryptoTests/BRCryptoDebugSupport.swift, bitcoin/BRWalletManager.c, bitcoin/BRWalletManager.h, bitcoin/BRWalletManagerEvent.c, bitcoin/BRWalletManagerPrivate.h, crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManager.h, crypto/BRCryptoWalletManagerClient.c, crypto/testCrypto.c
I included a depth in the sync recommended event. Should allow consumers to kick off a sync, if they deem the are in a state to do so, without having to determine where to start. Should give us flexibility in case other blockchains ever wanted to recommend a sync.
=> CORE-658: Add syncRecommended event

Swift/BRCrypto/BRCryptoSystem.swift
Created as a draft for now. Waiting to confirm BTC block height updates flow upwards in API case once BDB is back going.
=> CORE-661: Send blockUpdated event in Swift

Swift/BRCore.xcodeproj/project.pbxproj, generic/BRGenericRipple.c, ripple/BRRippleAccount.c, ripple/BRRippleAccount.h, ripple/BRRippleAddress.c, ripple/BRRippleAddress.h, ripple/BRRippleBase.h, ripple/BRRippleSerialize.c, ripple/BRRippleTransaction.c, ripple/BRRippleTransaction.h, ripple/BRRippleTransfer.c, ripple/BRRippleTransfer.h, ripple/BRRippleWallet.c, ripple/BRRippleWallet.h, ripple/testRipple.c
Added the BRRippleAddress files and functions
Modified the other classes to use address functions
Modified the unit test
**NOTE:** whenever BRRippleAddress objects are going "in" or "out" of one of our objects (wallet, transfer, etc) they are copied.  The caller always continues to own any BRRippleAddress they create or ask for so it is clear they must clean them up.
**NOTE:** did not change anything in the generic folder
=> CORE-684: In Core Ripple, Define BRRippleAddress.[ch]

crypto/testCrypto.c
Overlooked this test code, which produced a warning, when 'getTransfers' was added.
=> CORE-687: Add stub for `_CWMNopGetTransactionsGenCallback()` in `BRCr yptoCWMClientGEN`

crypto/BRCryptoPrivate.h, crypto/BRCryptoTransfer.c, crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManagerClient.c, generic/BRGeneric.c, generic/BRGeneric.h, generic/BRGenericBase.h, generic/BRGenericHandlers.h, generic/BRGenericManager.c, generic/BRGenericPrivate.h, generic/BRGenericRipple.c, ripple/BRRippleAccount.c, ripple/BRRippleAccount.h, ripple/BRRippleWallet.c, ripple/BRRippleWallet.h
Add BRGenericTransferDirection.
Add genWalletHasAddress() to support genTransferGetDirection()
Add BRGenericTransferState.
When recovering a GEN Transfer use the 'timestamp + blockHeight' values to fill out the transfer's state.  Update the GEN Transfer state on 'signed' and 'submitted'.
Compare GEN transfers based on the hash; don't extend wallet transfers unless the GEN hashes differ.
Add some ripple function for 'HasAddress'
=> CORE-624: Extend GEN architecture

hedera/BRHederaAccount.h, hedera/BRHederaAddress.c, hedera/BRHederaSerialize.c, hedera/BRHederaTransaction.c, hedera/testHedera.c
Add several unit tests to the BRHederaAddress code
as well as making the address code a bit more
robust with respect to parsing a string address.
1. Fix up any code related to the unit tests
2. Add some additional comments
3. Remove duplicate function declaration
=> CORE-700: Add unit tests to hedera

crypto/BRCryptoAccount.c
Change the account serialization version to 2 - which includes Ripple now.
=> CORE-692: Update BRCryptoAccount version (for ripple)

crypto/BRCryptoTransfer.c, crypto/BRCryptoTransfer.h, crypto/BRCryptoWallet.c
Implement `cryptoWalletGenerateBalance()` - used exclusively for a GEN wallet’s balance - with `cryptoTransferGetAmountDirectedNet()`.
=> CORE-699: Add cryptoTransferGetAmountDirectedNet

Swift/BRCrypto/BRCryptoSystem.swift
Confirmed that IOS does not touch SystemCallbackCoordinator.
=> CORE-539: SystemCallbackCoordinator need not be public

Java/CoreCrypto/src/androidTest/java/com/breadwallet/corecrypto/HelpersAIT.java, Java/Crypto/src/androidTest/java/com/breadwallet/crypto/BlockchainDbAIT.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/BlockchainDb.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/BdbApiClient.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/SubscriptionApi.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Subscription.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/SubscriptionCurrency.java, Java/Crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/SubscriptionEvent.java, Java/CryptoDemo/build.gradle, Swift/BRCrypto/common/BRBlockChainDB.swift, Swift/BRCryptoTests/BRBlockChainDBTest.swift
Fill out the unit tests.  Update the JWT token.
This does not address subscriptions in the Crypto interface; only connectivity to the BDB.
Requires Java changes.
=> CORE-715: Update BlockChainDB Subscription JSON types

ripple/BRRippleAddress.c, ripple/testRipple.c
Create specific bytes for the unknown address (or empty string)
Return "unknown" when the addres is our special array of bytes
Add unit tests
=> CORE-718: In Core ripple: handle unknown address

hedera/BRHederaTransaction.c, hedera/testHedera.c
When serializing a transaction - prepend 24 bytes to hold the
shard, realm, and accountid of the expected Hedera submission node
The Hedera java SDK being used on the server does not have any public function to get at the account node id from the serialized bytes - so we need to send them up.
=> CORE-712: In Core Hedera: Add "node account id" into serialized bytes

crypto/BRCryptoAccount.h, crypto/BRCryptoBase.h, crypto/BRCryptoCipher.c, crypto/BRCryptoCoder.c, crypto/BRCryptoCurrency.c, crypto/BRCryptoHash.c, crypto/BRCryptoHasher.c, crypto/BRCryptoKey.c, crypto/BRCryptoPrivate.h, crypto/BRCryptoSigner.c, crypto/BRCryptoStatus.c, crypto/BRCryptoStatus.h, crypto/BRCryptoTransfer.h, crypto/BRCryptoWalletManager.h, crypto/BRCryptoWalletManagerClient.h
- Removed include statements for BTC/ETH in public headers (i.e. not BRCryptoXyzPrivate.h headers)
- Moved functions declarations that used BTC/ETH/GEN types to BRCryptoPrivate.h.
- Added include statements for system headers uncovered by cleanup
Potentially controversial change is to the `BRCryptoCWMEthGetBlocksCallback` declaration in `BRCryptoWalletManagerClient.h`. It was of type `BREthereumSyncInterestSet`. To achieve removal of ETH headers there, needed to change to its alias (unsigned int). Alternatively, could add a typedef for it? Or could add the header back?
=> CORE-717: Remove BTC/ETH includes from public crypto headers

ethereum/util/BRUtilMathParse.c, ethereum/util/testUtil.c
Parsing of a string with a prefix of "0x" requires at least one digit after the "0x" prefix; ensure one exists.  Doing so ensures that 'parse (from string) <==> coerce (to string)' are reversible.
=> CORE-458: In `coerceStringPrefaced()` return "0x0", not "0x".

Swift/BRCrypto/BRCryptoSystem.swift
It was a mystery why it was failing before - but it does not fail anymore.
=> CORE-649: In Core Ripple, Fix precondition in GEN:funcSubmitTransaction

ethereum/util/BRUtilMathParse.c, ethereum/util/testUtil.c
Prior PR (for CORE-501) introduced an overly restrictive constraint in the parse.  The issue shows up when syncing the 'loan (mainnet)' wallet.
=> CORE-727: Handle an 'all zeros' string in createUInt256Parse()

Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/CoreCryptoApplication.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/TransferListActivity.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/WalletListActivity.java, Java/CryptoDemo/src/main/res/layout/layout_connect_with_peer.xml, Java/CryptoDemo/src/main/res/menu/menu_transfer_list.xml, Java/CryptoDemo/src/main/res/menu/menu_wallet_list.xml
@pbudelli asked about how to set a custom node for BTC so I added the functionality to the demo app.
Used the opportunity to add back the wipe-from-intent functionality (useful if the app is in a bad state on startup). Also removed the reset command (in CryptoDemo, was same as wipe command since the app doesn't have a list of selectable paper keys).
=> CORE-732: Add example of NetworkPeer in CryptoDemo

Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/CoreCrypto/src/main/java/com/breadwallet/corecrypto/WalletManager.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibraryDirect.java, Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManager.java, Java/Crypto/src/main/java/com/breadwallet/crypto/System.java, Java/CryptoDemo/src/main/java/com/breadwallet/cryptodemo/CoreSystemListener.java, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCryptoDemo/CoreDemoListener.swift, bitcoin/BRWalletManager.c, bitcoin/BRWalletManager.h, crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManager.h, ethereum/ewm/BREthereumEWM.c, ethereum/ewm/BREthereumEWM.h, generic/BRGenericWalletManager.c, generic/BRGenericWalletManager.h, support/BRFileService.c, support/BRFileService.h
Rather than adding an argument to `cryptoWalletManagerCreate()` of `wipe` which a) changes the interface, b) is only used once in a million, c) needs to be propagated down to the BWM, EWM and GWM so that the proper file can be wiped, I added a new function `cryptoWalletManagerWipe()` which propagates down to BWM, EWM and GWM and is called one time in a million via a function on `System`.
Reasonable?  Would need a Java analogue. 
Example in CoreDemoListener.swift:
```
if !success {
system.wipe (network: network)
let successRetry = system.createWalletManager (network: network,
mode: mode,
addressScheme: scheme,
currencies: currencies)
if !successRetry { UIApplication.doError(network: network) }
}
}		
```
=> CORE-722: Add `system.wipe()`

crypto/BRCryptoTransfer.c, crypto/BRCryptoTransfer.h
Couple of points to consider:
- I created one function (cryptoTransferCompare, ala cryptoAmountCompare); do we want/need more?
- Are you OK with the vanilla nature of the name? Since multiple facets are considered, couldn't come up with something else...
- I sorted "ascending", only because logically it was the simplest for me to reason; good with that?
- It reflects the sort algorithm we use both use in our demo apps (with timestamp thrown in); do we care about ordering for other states (besides INCLUDED)?
=> CORE-400: Add cryptoTransferCompare

bitcoin/BRPeerManager.c, bitcoin/BRSyncManager.c, bitcoin/BRWallet.c, bitcoin/BRWalletManager.c, support/BRBIP32Sequence.h
Couple commits here that do the following:
- Update the gap length used in BRWalletNew to account for bloom filter construction
- Update BRWalletManagerNew to handle BRWalletNew returning NULL
- Fix some "issues" in BRSyncManager (function call in macro means it was called twice, implicit cast)
For the "Update the gap length used in BRWalletNew to account for bloom filter construction" change, I tested by getting a wallet in the "bad state" outlined in the JIRA and then confirming that, with the fix, startup progressed normally.
For the "Update BRWalletManagerNew to handle BRWalletNew returning NULL" change, I tested by hitting each fail point in `BRWalletManagerNew` (via specific builds).
=> CORE-724: Handle BRWalletNew returning NULL in BRWalletManager

Java/CoreCrypto/src/androidTest/java/com/breadwallet/corecrypto/SystemAIT.java, Swift/BRCryptoTests/BRCryptoSystemTests.swift
Tests were failing here; updated Swift/Java to match up with the implementation.
=> CORE-738: Update testSystemAppCurrencies for API behaviour

Swift/BRCryptoDemo/CoreDemoAppDelegate.swift, bitcoin/BRWalletManager.c, ethereum/ewm/BREthereumEWM.c, support/BRFileService.c, support/BRFileService.h
I've tested this by aborting the Demo App after the 'clear' and before any 'save' within the BEGIN/COMMIT block.  The old DB content remained, with all blocks in existence before the 'clear'.
But, looking for a careful eye!
=> CORE-639: Define fileServiceReplace()

Swift/BRCore.xcodeproj/project.pbxproj, crypto/BRCryptoAddressP.h, crypto/BRCryptoBaseP.h, crypto/BRCryptoFeeBasis.c, crypto/BRCryptoFeeBasisP.h, crypto/BRCryptoHash.c, crypto/BRCryptoNetwork.c, crypto/BRCryptoNetworkP.h, crypto/BRCryptoTransfer.c, crypto/BRCryptoTransferP.h, crypto/BRCryptoWalletP.h, include/BRCryptoBase.h, include/BRCryptoFeeBasis.h, include/BRCryptoNetwork.h, include/BRCryptoTransfer.h
Requires no Swift change; seems no Java change either.
=> CORE-774: Remove `BRCryptoBlockChainType` from the public interface.

Swift/BRCrypto/BRCryptoNetwork.swift, Swift/BRCrypto/BRCryptoSystem.swift, crypto/BRCryptoNetwork.c, crypto/BRCryptoTransfer.c, include/BRCryptoNetwork.h, include/BRCryptoTransfer.h
=> CORE-761: For Swift enums w/ CustomStringConvertible use C Functions

Java/corecrypto/src/main/java/com/breadwallet/corecrypto/Wallet.java, Java/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryDirect.java, Java/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWallet.java, Java/crypto/src/main/java/com/breadwallet/crypto/Wallet.java, Java/cryptodemo-android/src/main/java/com/breadwallet/cryptodemo/CoreSystemListener.java, Swift/BRCrypto/BRCryptoWallet.swift, Swift/BRCryptoTests/BRCryptoBaseTests.swift, Swift/BRCryptoTests/BRCryptoTransferTests.swift, Swift/BRCryptoTests/BRCryptoWalletTests.swift, crypto/BRCryptoWallet.c, ethereum/ewm/BREthereumEWM.c, ethereum/ewm/BREthereumEWM.h, include/BRCryptoWallet.h
Add cryptoWalletHasAddress() with corresponding Swift and Java interfaces.
Also removes the 'getSourceAddress' functionality - it never really did anything except return the 'target' address.
=> CORE-778: Define cryptoWalletHasAddress

Java/corecrypto/src/commonTest/java/com/breadwallet/corecrypto/AmountAIT.java, Java/corecrypto/src/main/java/com/breadwallet/corecrypto/NetworkDiscovery.java, Java/corecrypto/src/main/java/com/breadwallet/corecrypto/Unit.java, Java/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryDirect.java, Java/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManager.java, Java/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/CurrencyDenomination.java, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/BRCryptoUnit.swift, Swift/BRCrypto/common/BRBlockChainDB.swift, Swift/BRCryptoTests/BRCryptoAmountTests.swift, Swift/BRCryptoTests/BRCryptoNetworkTests.swift, crypto/BRCryptoAccount.c, crypto/BRCryptoAccountP.h, crypto/BRCryptoNetwork.c, crypto/BRCryptoUnit.c, include/BRCryptoUnit.h
There was a inconsistency between the Unit::uids created by BlockchainDB.configure and by cryptoNetworkInstallBuiltins.  With this change, Unit::uids are created in `cryptoUnitCreate()` and BlockchainDB and BRCRyptoNetwork pass in the Unit::code.
Also, this change fixes some unit test errors and compilation errors.  And some inconsistencies between Java/Swift as regard Unit declaration.
=> CORE-791: Avoid Duplicate Unit Declarations

ripple/README.md, ripple/fundRippleAccount.js
The ripple testnet data gets deleted every 90 days - so we need
decent instructions on how to refund our Ripple wallet for testing
(FYI - Sam told me to put the instructions in this folder).
=> CORE:795: Add instructions for testing

Java/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoTransferAttribute.java, Java/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryDirect.java, Java/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryIndirect.java, Java/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManager.java, Java/cryptodemo-android/src/main/java/com/breadwallet/cryptodemo/TransferDetailsActivity.java, Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCrypto/common/BRBlockChainDB.swift, crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManagerClient.c, crypto/BRCryptoWalletManagerP.h, generic/BRGeneric.c, generic/BRGeneric.h, include/BRCryptoWalletManagerClient.h
[Currently built on CORE-805; I'll rebase once that PR is approved]
Needs a minimal change to update the Android UI for 'transfer detail' - add an 'Attributes' line.
=> CORE-804: Provide BlockSet metaData as 'TransferAttribute' data.

Java/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryIndirect.java
@EBGToo, no longer sure of the branching strategy but this is a hotfix required by the Android guys. I've slatedit against staging/core-5.0.0 (and created a `core-5.0.0-beta.2.hotfix.1` tag for them as well). Let's chat.
=> CORE-811: Add null check for JNA indirect native calls

ethereum/ewm/BREthereumEWMClient.c
Similar to CORE-811, hotfix requested by the Android guys. Amazingly, no reports from iOS for this issue despite it being in common code.
=> CORE-814: Set WALLET_EVENT_FEE_ESTIMATED status accordingly for failures

Java/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java, Java/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryDirect.java, Java/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryIndirect.java, Java/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManager.java, Swift/BRCrypto/BRCryptoSystem.swift, crypto/BRCryptoWalletManagerClient.c, generic/BRGeneric.h, generic/BRGenericHandlers.h, generic/BRGenericManager.c, generic/BRGenericRipple.c, include/BRCryptoWalletManagerClient.h, ripple/BRRipplePrivateStructs.h, ripple/BRRippleTransfer.c, ripple/BRRippleTransfer.h, ripple/BRRippleWallet.c
Propagate the BlockSet 'status' in Crypto C and then down to the GEN interface.  Add a `bool error` flag to XRP and account for an error when computing the GEN/XRP wallet's balance.
=> CORE-815: Add 'status' to `cwmAnnounceGetTransferItemGEN()`

Swift/BRCryptoTests/BRCryptoNetworkTests.swift
Change is to make the unit test consistent with BRCryptoConfig.h declarations for network fees.
=> CORE-821: Fix `testNetworkETH()`

Java/corecrypto/src/main/java/com/breadwallet/corecrypto/Utilities.java, Java/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoTransferState.java, Java/crypto/src/main/java/com/breadwallet/crypto/TransferConfirmation.java, Java/cryptodemo-android/src/main/java/com/breadwallet/cryptodemo/CoreCryptoApplication.java, Java/cryptodemo-android/src/main/java/com/breadwallet/cryptodemo/TransferDetailsActivity.java, Java/cryptodemo-android/src/main/java/com/breadwallet/cryptodemo/TransferListActivity.java, Swift/BRCrypto/BRCryptoTransfer.swift, Swift/BRCryptoDemo/TransferTableViewCell.swift, Swift/BRCryptoDemo/TransferViewController.swift, crypto/BRCryptoTransfer.c, crypto/BRCryptoWalletManager.c, crypto/BRCryptoWalletManagerClient.c, generic/BRGeneric.h, generic/BRGenericBase.h, generic/BRGenericManager.c, generic/BRGenericPrivate.h, include/BRCryptoTransfer.h
Modify BRCryptoTransferState for 'included' to add 'BRCryptoBoolean success; char error[...]' and follow through for all of Crypto, Gen, Swift, Java.
The Java 'JNA Struct' seems to cause a crash.. on 'String error'.
=> CORE-816: Extend TransferConfirmation with success:Bool, error:String?

Swift/BRCrypto/BRCryptoSystem.swift, Swift/BRCryptoTests/BRCryptoBaseTests.swift, Swift/BRCryptoTests/BRCryptoWalletManagerTests.swift, Swift/BRCryptoTests/BRCryptoWalletTests.swift, crypto/BRCryptoWalletManager.c, generic/BRGeneric.h, generic/BRGenericManager.c, include/BRCryptoWalletManager.h
[Will cherry-pick to WalletKit]
SBI noticed XRP events being inconsistent with BTC API/P2P Events.  Added GEN events in all the right places.  Added a unit test for XRP that uses the same 'checkManagerEventsCommonlyWith()` function.
Implemented genManager{Sync,SyncToDepth} - removed assert()
=> CORE-670: Generate GEN Wallet Manager Events.
